#! /bin/sh

sxhkd &
nitrogen --restore & 
bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width        2
bspc config window_gap		9
bspc config focused_border_color "#6599AA"
#bspc config focused_border_color "#0F7D73"
#bspc config focused_border_color "#cacaca"
bspc config normal_border_color "#282a36"
bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config single_monocle                false
bspc config bottom_padding                0
bspc config left_padding                  0
bspc config right_padding                 0



bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
polybar example -r
